version: '3.6'

services:
   artemis:
      image: vromero/activemq-artemis:2.4.0
      ports:
         - 61616:61616
         - 8161:8161
      environment: 
         - ARTEMIS_USERNAME=avelon
         - ARTEMIS_PASSWORD=bluechip
      hostname: artemis
      container_name: artemis
      networks:
         - artemis-test
   producer:
      build: 
         context: producer/
         args:
           jar: producer/build/libs/producer.jar
           port: 8081
      ports:
         - 8081:8081
      volumes:
         - artemis-test:/opt/
      hostname: producer
      container_name: producer
      networks:
         - artemis-test
      depends_on:
         - artemis
   consumer:
      build: 
        context: consumer/
        args: 
          jar: consumer/build/libs/consumer.jar
          port: 8082
      ports:
         - 8082:8082
      volumes:
         - artemis-test:/opt/
      hostname: consumer
      container_name: consumer
      networks:
         - artemis-test
      depends_on:
         - artemis
volumes:
  artemis-test:
    external: true
networks:
  artemis-test:
